[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cxr-foundation"
version = "2.0.0"
description = "Chest X-ray Foundation Models"
authors = [
    {name = "Google Health AI Developer Foundations Team"}
]
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://developers.google.com/health-ai-developer-foundations"
Documentation = "https://developers.google.com/health-ai-developer-foundations/overview"
Repository = "https://github.com/Google-Health/cxr-foundation"
Issues = "https://github.com/Google-Health/cxr-foundation/issues"

[tool.hatch.metadata.hooks.requirements_txt]
files = [
    "serving/requirements.txt",
    "clientside/requirements.txt"
]